language: java
sudo: false
install:
  - git clone https://github.com/indigo-iam/OpenID-Connect-Java-Spring-Server.git $HOME/mitreid-cnaf
  - cd $HOME/mitreid-cnaf && git checkout develop-1.3.x && mvn install && cd $HOME/indigo-iam/iam
addons:
  sonarcloud:
    organization: andreaceccanti-github
    token:
      secure: Q2VrpnSpskLti04/MZEUW9viFK/sKXP310p8TymCV8lka3c6465KjpTi87IIzKjEj8M+QICKEiTVTD446nyGMczmdjij29UND69MrVSMhFZfLSastIKmKvP99hiRUbiuQSJ/tow5mLPZk08IaEfYCMC2s1W5kq6ovfzVXPsUdkWNp7e767zyBNvgBgemyq5yPOtEZm4L2AiTkby6SGlWDWxSDw/IBWQ+Zc80KqQVAKW/Nmxg0GhWPPy2KA/jPIy4fdmbKI5+MyLPBgOWZITUpiV0dRSRIJyYVlt+Xikn6eujV6PR0vrBcOO62ncOx/1k69kUWCNC4Q0vv3RoBzCcFptWNBNwqq/U39Uz/mBnWjbRJ84hT3isYAPZ1B4+Ne6r1EqkmMUzzAPOEGP1wkHyz1O/k74NY/tzC7AuirZ779pBgSqQ9db+/Hts6w8GHTcHpHA3AiD8J3Sa4uWy1Z433z+76CXSxxak7LuZS8Qm/BO3CWSXblitY7Wjr6PAwybmUoY4cmNBSfm3EWXtpeIk8/2iaz0FzxTMegBzo2tJgEP1UvW6HulokNzwxRur2kGpGuS/08Gu0KZ9vzrpY7YIqCsnEy5G4niZ2ASUpItyw/IHHIW60DH9GBmiIBWVtkji7njynHIEua8hWdgGCa1VXAglnXJX27OTUh4B/HlBlN0=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
