language: java
sudo: required
services:
- docker
- mysql
dist: trusty
install:
- "/bin/bash travis/install-mitreid.sh"
addons:
  sonarcloud:
    organization: andreaceccanti-github
    token:
      secure: Q2VrpnSpskLti04/MZEUW9viFK/sKXP310p8TymCV8lka3c6465KjpTi87IIzKjEj8M+QICKEiTVTD446nyGMczmdjij29UND69MrVSMhFZfLSastIKmKvP99hiRUbiuQSJ/tow5mLPZk08IaEfYCMC2s1W5kq6ovfzVXPsUdkWNp7e767zyBNvgBgemyq5yPOtEZm4L2AiTkby6SGlWDWxSDw/IBWQ+Zc80KqQVAKW/Nmxg0GhWPPy2KA/jPIy4fdmbKI5+MyLPBgOWZITUpiV0dRSRIJyYVlt+Xikn6eujV6PR0vrBcOO62ncOx/1k69kUWCNC4Q0vv3RoBzCcFptWNBNwqq/U39Uz/mBnWjbRJ84hT3isYAPZ1B4+Ne6r1EqkmMUzzAPOEGP1wkHyz1O/k74NY/tzC7AuirZ779pBgSqQ9db+/Hts6w8GHTcHpHA3AiD8J3Sa4uWy1Z433z+76CXSxxak7LuZS8Qm/BO3CWSXblitY7Wjr6PAwybmUoY4cmNBSfm3EWXtpeIk8/2iaz0FzxTMegBzo2tJgEP1UvW6HulokNzwxRur2kGpGuS/08Gu0KZ9vzrpY7YIqCsnEy5G4niZ2ASUpItyw/IHHIW60DH9GBmiIBWVtkji7njynHIEua8hWdgGCa1VXAglnXJX27OTUh4B/HlBlN0=
jdk:
- openjdk8
script:
- "/bin/bash travis/build.sh"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  slack:
    on_success: always
    rooms:
      secure: eeLc5FlACOfYQ4MEvyUh+cO9pc8tAD1s9QwqO6FJjENHK/EPnPCTYpzq4Leqeoi78s6BZ9KwTQu975vsNobUPgrqAGEocE7n3FnBf2VKoXwr1c38suv/jWwUOZjgJyRbEUs0OdyzBGpLUps1Nlm+xN/DM7paUFskui6ofBzusDdcOv+9gKjdply0nuX+vETjCWE6smJ+9Xw4qrFu3nChRiQMp3fyrWcgJNnMjNinqofwUTWcwQXGb4i94LmWI0s8fJk9Gij/7FXH6xcZIpqYw92PlMSzmLaf/HpzjeZaMcqLhg/M+KWo1ognE2oKsdpLwP/9W+sqhrlZVMK118kjePq8274jzwfvLuwoyunFsU00lh6Zu0zAhxqZBuKt3BxRz/yhD63Q3RbRx7QyQ3aca4UbCv/76VhAzzSvRQ2sljx/Ep20nyeKemkfhdvA69WEMzgqyDI6gL/db4+SN21/l7j/C/35kJCvdYlmFIn6sKD7ET/Aive/26zd2GToSPZSvPQCgsn8bdtXbvTH5tMKmk/3ANwrE3SNLXc/+zTIqzrF6iYficqdEmA3T3+F+05Fp7zhAYPvsiUSS6g3OR2g5+bNlotz+xH34lnoK3BizHPvJC4bU0ykEYX0oT1MvoA0dJ9zXutFYb779fkdJioDCLqnKO9DZwARwTccj+rlpkg=
