language: java
sudo: required
services:
- docker
- mysql
dist: trusty
install:
- "/bin/bash travis/install-mitreid.sh"

addons:
  sonarcloud:
    organization: infn
    token:
			secure: h/xDLY0dBMCpMBKR6Ss0mEhMUD8lJ6KKo478VOmxiW3f1gEbQq+OvcqBCbUKCikkcsjxWe5WRG2UqmNl7TZjRqmTj2D1QJ5yz3QNHmAT6CLeecSq+WWSm9paydxjIyMgn3naeKOxkwZ6HrpFFapjsryHpjD05IeElocIeQb2wQDwODdcpWPByGkA7bD6iLKO8WXkQd+xPctts0aSp6yNd8xaRCUx7CmAc5dv8Sw5w8AOqUem5Ae/a3Fs+IEr+DAherQUG8Pua7UvuPTA32PNCOlMpa7KpBdW0k58EiKPaYEdbSwQSWhnemi7gve+snupZ9yPVRiB/yM779tiiRR6m9lwpLRk5LfbkBcSqg+85i6JdbCDosOH5em4KGGbI/Y+B1UF4x55NEK/JUU/R1q4LdTcuAyYJlSVAuQWbOYpijF4mEaFpnJm6JsK7m6Yh4CogwquOho42cjcVfO09/kgDlBDRcV7xqCk0JZS17WU44eZK7gOd9NQtVk18RqKUnDTK+dICdmU1QjIXFsNu3FIS5fnhRSp+w4jnyTy5wOu7coYhHv2Mg1QwNOSjNywzEI7GDY5dgw/z4V7TLvvLByDNLQe+7x2z0aMCfag2JIXKFCrj/FliXszWVLR3irKFC2eo5NLMESqPb3Z3qg7L6Pvge7QT6xz7GTUh0oTMEnLSPE=

jdk:
- openjdk8
script:
- "/bin/bash travis/build.sh"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

notifications:
  slack:
    on_success: always
    rooms:
      secure: eeLc5FlACOfYQ4MEvyUh+cO9pc8tAD1s9QwqO6FJjENHK/EPnPCTYpzq4Leqeoi78s6BZ9KwTQu975vsNobUPgrqAGEocE7n3FnBf2VKoXwr1c38suv/jWwUOZjgJyRbEUs0OdyzBGpLUps1Nlm+xN/DM7paUFskui6ofBzusDdcOv+9gKjdply0nuX+vETjCWE6smJ+9Xw4qrFu3nChRiQMp3fyrWcgJNnMjNinqofwUTWcwQXGb4i94LmWI0s8fJk9Gij/7FXH6xcZIpqYw92PlMSzmLaf/HpzjeZaMcqLhg/M+KWo1ognE2oKsdpLwP/9W+sqhrlZVMK118kjePq8274jzwfvLuwoyunFsU00lh6Zu0zAhxqZBuKt3BxRz/yhD63Q3RbRx7QyQ3aca4UbCv/76VhAzzSvRQ2sljx/Ep20nyeKemkfhdvA69WEMzgqyDI6gL/db4+SN21/l7j/C/35kJCvdYlmFIn6sKD7ET/Aive/26zd2GToSPZSvPQCgsn8bdtXbvTH5tMKmk/3ANwrE3SNLXc/+zTIqzrF6iYficqdEmA3T3+F+05Fp7zhAYPvsiUSS6g3OR2g5+bNlotz+xH34lnoK3BizHPvJC4bU0ykEYX0oT1MvoA0dJ9zXutFYb779fkdJioDCLqnKO9DZwARwTccj+rlpkg=
