language: java
sudo: required
services:
- docker
- mysql
dist: trusty
install:
- "/bin/bash travis/install-mitreid.sh"
addons:
  sonarcloud:
    organization: andreaceccanti-github
    token:
      secure: Q2VrpnSpskLti04/MZEUW9viFK/sKXP310p8TymCV8lka3c6465KjpTi87IIzKjEj8M+QICKEiTVTD446nyGMczmdjij29UND69MrVSMhFZfLSastIKmKvP99hiRUbiuQSJ/tow5mLPZk08IaEfYCMC2s1W5kq6ovfzVXPsUdkWNp7e767zyBNvgBgemyq5yPOtEZm4L2AiTkby6SGlWDWxSDw/IBWQ+Zc80KqQVAKW/Nmxg0GhWPPy2KA/jPIy4fdmbKI5+MyLPBgOWZITUpiV0dRSRIJyYVlt+Xikn6eujV6PR0vrBcOO62ncOx/1k69kUWCNC4Q0vv3RoBzCcFptWNBNwqq/U39Uz/mBnWjbRJ84hT3isYAPZ1B4+Ne6r1EqkmMUzzAPOEGP1wkHyz1O/k74NY/tzC7AuirZ779pBgSqQ9db+/Hts6w8GHTcHpHA3AiD8J3Sa4uWy1Z433z+76CXSxxak7LuZS8Qm/BO3CWSXblitY7Wjr6PAwybmUoY4cmNBSfm3EWXtpeIk8/2iaz0FzxTMegBzo2tJgEP1UvW6HulokNzwxRur2kGpGuS/08Gu0KZ9vzrpY7YIqCsnEy5G4niZ2ASUpItyw/IHHIW60DH9GBmiIBWVtkji7njynHIEua8hWdgGCa1VXAglnXJX27OTUh4B/HlBlN0=
jdk:
- openjdk8
script:
- "/bin/bash travis/build.sh"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  slack:
    rooms:
      on_success: always
      secure: Z6djACiF7i8y3pkWOTpqf3rQ58MlREYMiJmkrkKAyf64nCCYNw/GG6/wt8m8N6K9mtDrSKFG1KQPqeNlEfQerTAviUZwTMAsO5Idu7flfr7K23GxIWUf/dzIovH6TWEgpXS9xxS/QYMJT+3SGYTo2fuCQFKHYM9lIOX+UncMH8WfA/mIqXllOA0tqZ3nHWys2jUlWsjpedRMLllM9AL28Tw2ZVrRJWKJ/O49IJuOVw2VXLgjTfiiEg9ZK3E6fOWEVyZhIp9QvwZn1ksNylCSJ7GrJdEy4GTO4EIxaB+J6QvbO3ioaGkw3ZgDhkafaVZB443Gha0ZnBkqIlZ82xKYpcaljL9/kt892P7WokZ88YNEcBA/UkEf5kZ37ugZ51OZX+sH2Raj3ZqJdpAstNgq/DHgvHDO5MatJ16pAMEV3S6JeYHQC76/VT9XtKr2dQb80aoyCDNwUrIh6oO7gJogPNuOPZcjqhVNpGn4Az8PW9QWbAoxSuyMP2B7YvQ10i8yDH5++fUT3BrfBtqll0ALoKPZHLJJTFAICkAatjV1omfivP3kQ2sCxAoAQFaSzyEdIHcF+Bn2I9Q314dzxOAUmNG6cqoqDUvQzPAK25bIgqxVVU0IDJDyAiLAVlt1pnkjOHhO+6slv1faB0KfVqg5wNlucO/nxkZT2F6erH9MySk=
