iam:
  build: .
  dockerfile: ./docker/Dockerfile
  domainname: local.io

  environment:
    IAM_JAVA_OPTS: -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1044
    IAM_JAR: /code/target/mitreid-connect-boot-0.0.1-SNAPSHOT.war
    IAM_HOST: dev.local.io
    IAM_PORT: 8080

  ports:
    - "1044:1044"
    - "8080:8080"

  volumes:
    - .:/code:ro
