server:
  port: 9090

iam:
  baseUrl: http://localhost:${server.port}
  issuer: ${iam.baseUrl}/
  token:
    lifetime: 86400
  organisation:
    name: test

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/oic
#    username: oic
#    password: oic

  application:
    name: IAM

  jpa:
      properties:
        show-sql: true
        generate-ddl: true
        hibernate.format_sql: true

  h2:
    console:
      enabled: false

  profiles:
    active: dev

  resources:
    chain:
      enabled: true

idp:
  list: mitre,google

  mitre:
    issuer: http://mitre-srv:8080/openid-connect-server-webapp/
    client:
      id: client_id
      secret: client_secret
      redirectUri: ${iam.baseUrl}/openid_connect_login
    auth:
      scope: openid,profile,email,address,phone
    admin: 90342.ASDFJWFA

  google:
    issuer: https://accounts.google.com
    client:
      id: ...
      secret: ...
      redirectUri: ${iam.baseUrl}/openid_connect_login
    auth:
      scope: openid,profile,email,address,phone
    admin: 90342.ASDFJWFA


github:
  client:
    clientId: ...
    clientSecret: ...
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://localhost:9090/social_login
    useCurrentUri: false
    scope: user:email
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG

