server:
  port: 9090

iam:
  baseUrl: http://localhost:${server.port}
  issuer: ${iam.baseUrl}/
  token:
    lifetime: 86400
  organisation: 
    name: test

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/oic
#    username: oic
#    password: oic
     
  application:
    name: IAM 
    
  jpa:
      properties:
        show-sql: true
        generate-ddl: true
        hibernate.format_sql: true    

  h2:
    console:
      enabled: false
      
      
  profiles:
    active: dev
    
idp:
  baseUrl: http://mitre-srv:8080/openid-connect-server-webapp
  issuer: ${idp.baseUrl}/
  authorizeUrl: ${idp.baseUrl}/authorize
  tokenUrl: ${idp.baseUrl}/token
  userinfoUrl: ${idp.baseUrl}/userinfo
  jwkUrl: ${idp.baseUrl}/jwk
  client:
    id: client_id
    secret: client_secret
    redirectUri: ${iam.baseUrl}/openid_connect_login
  auth:
    scope: openid,profile,email,address,phone
