server:
  port: 8080

iam:
  issuer: http://${IAM_HOST:localhost}:${IAM_PORT:8080}/
  token:
    lifetime: 86400

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
     
  application:
    name: IAM 
    
  jpa:
      properties:
        show-sql: true
        generate-ddl: true

  h2:
    console:
      enabled: false
      
      
  profiles:
    active: dev