security:
  filter-order: 1 
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp
      pattern: "%a asdasd"

  use-forward-headers: ${IAM_USE_FORWARDED_HEADERS:false}

spring:
  application:
    name: INDIGO IAM
  jpa:
    generate-ddl: true
        
  profiles:
    active: google


iam:
  baseUrl: ${IAM_BASE_URL:http://localhost:8080}
  issuer: ${IAM_ISSUER:http://localhost:8080/}
  
  token:
    lifetime: 86400
  
  organisation:
    name: indigo-dc
  
  keyStoreLocation: ${IAM_KEY_STORE_LOCATION:classpath:keystore.jwks}

x509:
  trustAnchorsDir: ${IAM_X509_TRUST_ANCHORS_DIR:/etc/grid-security/certificates}
  trustAnchorsRefreshMsec: ${IAM_X509_TRUST_ANCHORS_REFRESH:14400} 
  
google:
    issuer: https://accounts.google.com
    
    client:
      clientId: ${IAM_GOOGLE_CLIENT_ID:define_me_please}
      clientSecret: ${IAM_GOOGLE_CLIENT_SECRET:define_me_please}
      redirectUris: ${IAM_GOOGLE_CLIENT_REDIRECT_URIS:${iam.baseUrl}/openid_connect_login}
      scope: openid,profile,email,address,phone


github:
  client:
    clientId: ${IAM_GITHUB_CLIENT_ID:define_me_please}
    clientSecret: ${IAM_GITHUB_CLIENT_SECRET:define_me_please}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://${iam.baseUrl}/gh_login
    useCurrentUri: false
    scope: user:email
  resource:
    userInfoUri: https://api.github.com/user 
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

flyway:
  locations:
    - classpath:db/migration/h2
---
spring:
  profiles: prod
  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://${IAM_DB_HOST:dev.local.io}:${IAM_DB_PORT:3306}/${IAM_DB_NAME:iam}
    username: ${IAM_DB_USERNAME:iam}
    password: ${IAM_DB_PASSWORD:pwd}
    max-active: ${IAM_DB_MAX_ACTIVE: 20}
    initial-size: ${IAM_DB_INITIAL_SIZE: 8}
    test-while-idle: ${IAM_DB_TEST_WHILE_IDLE: true}
    test-on-borrow: ${IAM_DB_TEST_ON_BORROW: true}
    validation-query: ${IAM_DB_VALIDATION_QUERY: SELECT 1}
    time-between-eviction-runs-millis: ${IAM_DB_TIME_BETWEEN_EVICTION_RUNS_MILLIS: 5000}
    min-evictable-idle-time-millis: ${IAM_DB_MIN_EVICTABLE_IDLE_TIME_MILLIS: 60000}
  
  jpa:
    openInView: false
    
flyway:
  locations:
    - classpath:db/migration/mysql
