spring:
  mvc:
    view:
      suffix: .html

server:
  context-path: /iam-test-client
  port: ${IAM_CLIENT_PORT:9090}
  use-forward-headers: ${IAM_CLIENT_USE_FORWARD_HEADERS:false}

iam:
    issuer: ${IAM_CLIENT_ISSUER:http://localhost:8080/}

    client:
      clientId: ${IAM_CLIENT_ID:client}
      clientSecret: ${IAM_CLIENT_SECRET:secret}
      redirectUris: ${IAM_CLIENT_REDIRECT_URIS:http://localhost:9090/iam-test-client/openid_connect_login}
      scope: ${IAM_CLIENT_SCOPES:openid,profile,email,address,phone,offline_access}
