saml:
  entity-id: ${IAM_SAML_ENTITY_ID:urn:iam:iam-devel}
  keystore: ${IAM_SAML_KEYSTORE:classpath:/saml/samlKeystore.jks}
  keystore-password: ${IAM_SAML_KEYSTORE_PASSWORD:password}
  key-id: ${IAM_SAML_KEY_ID:iam}
  key-password: ${IAM_SAML_KEY_PASSWORD:password}
  max-assertion-time-sec: ${IAM_SAML_MAX_ASSERTION_TIME:3000}
  max-authentication-age-sec: ${IAM_SAML_MAX_AUTHENTICATION_AGE:86400}
  id-resolvers: ${IAM_SAML_ID_RESOLVERS:eduPersonUniqueId,eduPersonTargetedId,eduPersonPrincipalName}
  metadata-lookup-service-refresh-period-sec: ${IAM_SAML_METADATA_LOOKUP_SERVICE_REFRESH_PERIOD_SEC:600}
  login-button-text: ${IAM_SAML_LOGIN_BUTTON_TEXT:Sign in with SAML}
  idp-entity-id-whilelist: ${IAM_SAML_IDP_ENTITY_ID_WHITELIST}
  
  jit-account-provisioning:
    enabled: ${IAM_SAML_JIT_ACCOUNT_PROVISIONING_ENABLED:false}
    trusted-idps: ${IAM_SAML_JIT_ACCOUNT_PROVISIONING_TRUSTED_IDPS:all}
    cleanup-task-enabled: ${IAM_SAML_JIT_ACCOUNT_PROVISIONING_CLEANUP_TASK_ENABLED:false}
    cleanup-task-period-sec: ${IAM_SAML_JIT_ACCOUNT_PROVISIONING_CLEANUP_TASK_PERIOD_SEC:86400}
    inactive-account-lifetime-days:  ${IAM_SAML_JIT_ACCOUNT_PROVISIONING_INACTIVE_ACCOUNT_LIFETIME_DAYS:15}
  
  idp-metadata: 
    - 
      metadata-url: ${IAM_SAML_IDP_METADATA:classpath:/saml/idp-metadata.xml}
      require-valid-signature: ${IAM_SAML_METADATA_REQUIRE_VALID_SIGNATURE:false}
      require-sirtfi: ${IAM_SAML_METADATA_REQUIRE_SIRTFI:false}
      require-rs: ${IAM_SAML_METADATA_REQUIRE_RS:false}
