spring:
  profiles:
    include: mysql,google,registration,saml

notification:
  disable: true

 
flyway:
  locations:
    - classpath:db/migration/mysql
    - classpath:db/migration/test

management:
  health:
    mail:
      enabled: false